default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: lengchuanbao
  password:

development:
  <<: *default
  database: property_dev

test: &test
  <<: *default
  database: property_test

production:
  <<: *default
  database: property_production
  pool: 20